name: Prepare for Android
description: Prepares Android runtime (ie. installs java and sets everything up)
runs:
  using: composite
  steps:
    - name: Set VERSION_* variables (apk)
      shell: bash
      run: |
        if [ "${{ github.ref_type }}" == "branch" ]; then
          versionName="$(jq -c -r -M ".." .release-please-manifest.json | tail -1)-SNAPSHOT"
        else
          versionName=${{ github.ref_name }}
        fi
        echo "VERSION_NAME=$versionName" >> gradle.properties